Feature: Live edit .vue files durn development
ph1p/vuepress-jsdoc pull request #40
Opened 2021-02-27 12:37 UTC by RCK-DEV

I've added a feature in which vuepress-jsdoc only regenerates the Vue source files which are modified during development (`yarn dev`). 

To run in live-edit mode execute `yarn run dev-live`

For the live edit feature i've used the current code inside the generate function (_cmds/index.js_) and extracted it into separate functions. Thus not altering the original generate code for now.

When the commander executes the generate functions it checks if the `--live` flag is set and determines if it must generate all docs or only which are currently modified.

My decision not to alter the original generate function results into a lot of duplicate code, but i would eventually like to refactor everything inside the `index.js` file so that the newly extracted functions (e.g. `parseFrontmatter, generateVueMdFileData`, ..) will be utilised. I believe this will improve the overall code quality.

### Know issues:

- `UnhandledPromiseRejectionWarning` caused whenever `.vue` files contains invalid syntax, a new `.vue` files gets created or deleted. Requires rerunning `yarn dev-live`.
- When adding or removing `.vue` file side will not get updated.

2021-03-01 10:15 UTC, ph1p commented
Thanks @RCK-DEV ! 
Really like this feature and can't wait to test it (:
I only have one small comment and that is that this project currently uses npm. Could you change it to npm, as there is now a deleted package.lock and an added yarn.lock in the changes?

2021-03-01 10:19 UTC, RCK-DEV commented
Ofcourse! I'll change it to npm. Glad to hear. 😃 I'm currently also working on some other features at the moment. I'll keep you posted. 👍🏻🙃

2021-03-03 20:01 UTC, ph1p requested changes

2021-03-03 20:01 UTC, ph1p commented on package.json
> +  "name": "@rck-dev/vuepress-jsdoc",
Please leave it as it was. It's ok if you publish your own version, but it should go out here.

2021-03-03 20:01 UTC, ph1p commented on package.json
> +  "version": "3.6.2",
I'm ok with a bump to 3.5.0

2021-03-03 20:01 UTC, ph1p commented on package.json
> +    "url": "https://github.com/RCK-DEV/vuepress-jsdoc#feature/multi-nav-sidebar",
Please leave it as it was.

2021-03-03 20:01 UTC, ph1p commented on package.json
> +    "chokidar": "^3.5.1",
Please move this up to the dependencies.

2021-03-03 20:01 UTC, ph1p commented on example/package.json
> +    "docs-multi-mono": "yarn docs --multinav --monorepo",
Please use `npm run`, to keep it consistent

2021-03-03 20:44 UTC, RCK-DEV commented on package.json
> +    "url": "https://github.com/RCK-DEV/vuepress-jsdoc#feature/multi-nav-sidebar",
This wasn't meant to be PR'ed. My bad. I've placed a fork on NPM only for development purposes. I'll put it back. 👍🏻

2021-03-03 21:07 UTC, ph1p commented on package.json
> +    "url": "https://github.com/RCK-DEV/vuepress-jsdoc#feature/multi-nav-sidebar",
All good (: I'll do a final review tomorrow and then hopefully merge everything. Good job!

2021-03-04 19:37 UTC, ph1p commented
Oh ok I totally misunderstood the PR. I thought that this is already ready for review, but there are still a few "TODO" or "WIP" places in it. 😅

Keep up the great work! 

A little tip from me. The PR is already a bit big and has apparently a few more features than just the live update of the content. Try to split it up a little bit. It is not bad if there are several PRs (:

2021-03-04 20:58 UTC, RCK-DEV commented
I believe i did another PR by accident a few days ago. 🙈 My bad haha. If you could decline this one than i'll redo my PR's when I'm ready. And in smaller chunks like you said. 😃

2021-03-04 21:08 UTC, ph1p commented
All good (: Take your time and play around with the code. I'll close this one and look forward to your changes.

2021-03-04 21:08 UTC, closed without merging